// Generated by KMM Resources
package com.softeq.resources

class L {
  companion object {
    val general: General = General()
  }
  class General {
    operator fun get(key: String): String? = when(key) {
      "mainScreen" -> mainScreen()
      "settingsScreen" -> settingsScreen()
      "diagramScreen" -> diagramScreen()
      "save" -> save()
      "textSize" -> textSize()
      "goToBack" -> goToBack()
      "goToSetting" -> goToSetting()
      "goToDiagram" -> goToDiagram()
      "close" -> close()
      else -> null
    }
  }
}


expect fun L.General.close(): String
expect fun L.General.diagramScreen(): String
expect fun L.General.goToBack(): String
expect fun L.General.goToDiagram(): String
expect fun L.General.goToSetting(): String
expect fun L.General.mainScreen(): String
expect fun L.General.save(): String
expect fun L.General.settingsScreen(): String
expect fun L.General.textSize(): String
